server:
  port: ":8080"

Brokers: "localhost:9092" 
Topic: "email"
MessageKey: "message"
LevelKey: "level"
TimeKey: "time"
CallerKey: "caller"
database: "email"
collection: "swap1,swap2"
GroupName: "Email-Group"
collection1: "starting"