server:
  port: ":8080"

Brokers: "localhost:9092" 
Topic: "email"
MessageKey: "message"
LevelKey: "level"
TimeKey: "time"
CallerKey: "caller"
database: "email"
collection: "db1,db2,db3"
GroupName: "sms"